version: '3.5'

services:
  postgres:
    container_name: postgres_container
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: dudevs
      POSTGRES_PASSWORD: dudevs
      #PGDATA: /data/postgres
    volumes:
       - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    #expose:
    #  - 5432
    restart: unless-stopped